-- ==========================================
-- DATABASE
-- ==========================================
CREATE DATABASE IF NOT EXISTS seed_track_db;
USE seed_track_db;

-- ==========================================
-- TBL_USER
-- ==========================================
CREATE TABLE TBL_USER (
    ID_USER INT AUTO_INCREMENT PRIMARY KEY,
    USERNAME VARCHAR(4) NOT NULL UNIQUE,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME VARCHAR(100) NOT NULL,
    ROLE ENUM('ADMIN', 'STAFF') NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL
);

-- ==========================================
-- TBL_MUNICIPALITY
-- ==========================================
CREATE TABLE TBL_MUNICIPALITY (
    ID_MUNICIPALITY INT AUTO_INCREMENT PRIMARY KEY,
    TOWN VARCHAR(100) NOT NULL,
    PROVINCE VARCHAR(100) NOT NULL
);

-- ==========================================
-- TBL_REQUESTER
-- ==========================================
CREATE TABLE TBL_REQUESTER (
    ID_REQUESTER INT AUTO_INCREMENT PRIMARY KEY,
    ID_FK_MUNICIPALITY INT NOT NULL,
    F_NAME VARCHAR(100) NOT NULL,
    L_NAME VARCHAR(100) NOT NULL,
    AGENCY VARCHAR(150) NOT NULL,
    EMAIL_ADD VARCHAR(150) NOT NULL,

    CONSTRAINT FK_REQUESTER_MUNICIPALITY
        FOREIGN KEY (ID_FK_MUNICIPALITY)
        REFERENCES TBL_MUNICIPALITY(ID_MUNICIPALITY)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ==========================================
-- TBL_REQUEST
-- ==========================================
CREATE TABLE TBL_REQUEST (
    ID_REQUEST INT AUTO_INCREMENT PRIMARY KEY,
    ID_FK_REQUESTER INT NOT NULL,
    TRACKING_NO VARCHAR(20) NOT NULL UNIQUE,
    DATE_REQ DATE NOT NULL,
    WEIGHT_REQ INT NOT NULL,
    STUDY_TITLE VARCHAR(255) NOT NULL,
    STATUS ENUM(
        'PENDING',
        'APPROVED',
        'REJECTED',
        'DISPATCHED'
    ) DEFAULT 'PENDING',
    DATE_APPROVED DATE NULL,
    DATE_DISPATCHED DATE NULL,

    CONSTRAINT FK_REQUEST_REQUESTER
        FOREIGN KEY (ID_FK_REQUESTER)
        REFERENCES TBL_REQUESTER(ID_REQUESTER)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ==========================================
-- TBL_GID
-- ==========================================
CREATE TABLE TBL_GID (
    GID INT AUTO_INCREMENT PRIMARY KEY,
    ACC_NO VARCHAR(20) NOT NULL UNIQUE,
    ACC_NAME VARCHAR(150) NOT NULL
);

-- ==========================================
-- TBL_ACTIVE
-- ==========================================
CREATE TABLE TBL_ACTIVE (
    ID_ACTIVE INT AUTO_INCREMENT PRIMARY KEY,
    ID_FK_GID INT NOT NULL,
    CURRENT_WEIGHT INT NOT NULL,
    VIABILITY DECIMAL(2,1) NOT NULL,
    BARCODE VARCHAR(30) NOT NULL UNIQUE,
    STOCK_ONHAND INT NOT NULL,
    LOCATION VARCHAR(20) NOT NULL,
    AVAILABILITY ENUM(
        'AVAILABLE',
        'UNAVAILABLE',
        'RESERVED'
    ) DEFAULT 'AVAILABLE',

    CONSTRAINT FK_ACTIVE_GID
        FOREIGN KEY (ID_FK_GID)
        REFERENCES TBL_GID(GID)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

-- ==========================================
-- TBL_REQUEST_LINEITEM
-- ==========================================
CREATE TABLE TBL_REQUEST_LINEITEM (
    ID_LINEITEM INT AUTO_INCREMENT PRIMARY KEY,
    FK_TRACKING_NO VARCHAR(20) NOT NULL,
    FK_BARCODE VARCHAR(30) NOT NULL,
    STOCK_OUT INT NOT NULL,

    CONSTRAINT FK_LINEITEM_REQUEST
        FOREIGN KEY (FK_TRACKING_NO)
        REFERENCES TBL_REQUEST(TRACKING_NO)
        ON UPDATE CASCADE
        ON DELETE CASCADE,

    CONSTRAINT FK_LINEITEM_ACTIVE
        FOREIGN KEY (FK_BARCODE)
        REFERENCES TBL_ACTIVE(BARCODE)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);



ALTER TABLE TBL_ACTIVE
ADD COLUMN SEED_NAME VARCHAR(100) NOT NULL
AFTER ID_FK_GID;

ALTER TABLE TBL_REQUEST 
ADD COLUMN DEADLINE_DATE DATE NULL AFTER DATE_REQ;